### ISSUE TITLE
What exactly does the sample show?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [minsik-ai/Kamera#1]
All I see is camera preview and that's it.
There's nothing else to see and nothing else to press (other than license list)

**Comment by minsik-ai** [comment]
You are correct, it is the only implementation.
The sample is the Kotlin source code itself, designed in such a way that is appropriate for the purpose.
Some of the ways this repo can be useful to you : 

1. Good starting project for your own app utilizing camera preview w/ OpenGL customization.
2. Studying the source code to learn basic Kotlin syntax and how to utilize its features cleanly.
3. A companion to [Android Graphics Architecture](https://source.android.com/devices/graphics/architecture) document, as a more modern version of [Grafika](https://github.com/google/grafika).

**Comment by AndroidDeveloperLB** [comment]
But the repo description says:

> Sample Android app for showcasing custom implementation of OpenGL camera preview display, written in Kotlin.

Where's this shown here...

**Comment by AndroidDeveloperLB** [comment]
:(
